### ISSUE TITLE
issues installing the 'share' extension

### ISSUE THREAD

**Issue by amygdala** [gclouduniverse/gcp-notebook-share-dlvm-extension#12]
(Following the instructions here: https://blog.kovalevskyi.com/share-your-notebooks-with-one-click-b98ed3e856bb)

There's a typo in the [install script](https://github.com/gclouduniverse/gcp-notebook-share-dlvm-extension/blob/master/install.sh): 

instal --> install

Though even after fixing that, I see this error when running the script: "Missing extension module "lib/index.js"

Can provide more of a trace if need be.

**Comment by b0noI** [comment]
Looks like they (JupyterLab) have renamed the plugin: https://github.com/jupyterlab/jupyterlab/blob/80fc94646375e8fdd593971b2ec3af79a70a3b11/docs/source/getting_started/changelog.rst#L132

error: src/index.ts(26,5): error TS2305: Module '"/home/jupyter/share/node_modules/@jupyterlab/application/lib/index"' has no exported member 'JupyterLabPlugin'.

**Comment by b0noI** [comment]
fixed in https://github.com/gclouduniverse/gcp-notebook-share-dlvm-extension/tree/v0.1.1
