### ISSUE TITLE
Create webpage with details

### ISSUE THREAD

**Issue by Glebuar** [gclouduniverse/gcp-notebook-share-dlvm-extension#4]

**Comment by b0noI** [comment]
also add link from our UI extension

**Comment by Glebuar** [comment]
Please, enable GitHub Pages in repository settings.

**Comment by b0noI** [comment]
done, also I have attached DNS name: nbshare.cloud

**Comment by Glebuar** [comment]
What information should be added to the web page?

**Comment by b0noI** [comment]
details page that explains how sharing works:
* creates GCS bucket
* uploads to GCS
* etc...

customers usually would like to know how extension works before using it
